name: Build and Deploy ASP.NET 4.8 Application

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  # ASP.NET 4.8 requires Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore ASPDotNetSampleWebapp.sln

    - name: Build the solution
      run: msbuild ASPDotNetSampleWebapp.sln /p:Configuration=Release
      
   
    - name: List files in output directory  # Check if files are present
      run: |
        OUTPUT_DIR="D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release\net48"
        if (Test-Path $OUTPUT_DIR) {
            dir $OUTPUT_DIR
        } else {
            echo "Output directory does not exist."
            exit 1  # Exit with error if the directory does not exist
        }

    - name: Publish the project
      run: |
        OUTPUT_DIR="D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release\net48"
        mkdir publish
        if (Test-Path $OUTPUT_DIR) {
            xcopy /s /e /y /i "$OUTPUT_DIR\*" "publish"
        } else {
            echo "No files to copy from output directory."
            exit 1  # Exit with error if no files to copy
        }

      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aspnet_app
        path: publish
