name: Build and Deploy ASP.NET 4.8 Application

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  # ASP.NET 4.8 requires Windows environment

    steps:
   # Ensure the release directory exists
    - name: Ensure Release Directory Exists
      run: |
        $releaseDir = "D:\a\DotNet\DotNet\release"
        if (!(Test-Path -Path $releaseDir)) {
            New-Item -ItemType Directory -Path $releaseDir
            echo "Release directory created at $releaseDir."
        } else {
            echo "Release directory already exists at $releaseDir."
        }
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore ASPDotNetSampleWebapp.sln

    - name: Build the solution
      run: msbuild ASPDotNetSampleWebapp.sln /p:Configuration=Release
    
   

    # Publish the project
    - name: Publish the project
      run: |
        mkdir publish
        xcopy /s /e /y /i "D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\ASPDotNetSampleWebapp\*" "publish"

    # Upload Build Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aspnet_app
        path: publish
