name: Build and Deploy ASP.NET 4.8 Application

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  # ASP.NET 4.8 requires Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore ASPDotNetSampleWebapp.sln

    - name: Build the solution
      run: msbuild ASPDotNetSampleWebapp.sln /p:Configuration=Release
      
   
    - name: List files in output directory  # Check if files are present
      run: |
        if (Test-Path "D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release\net48") {
            dir "D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release\net48"
        } elseif (Test-Path "D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release") {
            dir "D:\a\DotNet\DotNet\ASPDotNetSampleWebapp\bin\Release"
        } else {
            echo "Output directory does not exist."
        }
 
   
    - name: Publish the project
      run: |
        mkdir publish
        xcopy /s /e /y /i "D:\Project\DotNet\ASPDotNetSampleWebapp\bin\Release\net48\*" "publish" || echo "No files to copy."
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aspnet_app
        path: publish
